version: '3.3'

services:

  template-sql:
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'templateuser'
      MYSQL_PASS: 'templatepassword'
    volumes:
      - ./template-sql/mysql_data:/var/lib/mysql
    ports:
      - "33000:3306"
    expose:
      - "33000"
    networks:
      - template-rest-sql-net


  template-rest:
    build: ./template/
    volumes:
      - ./.m2:/root/.m2
    ports:
      - "9001:8080"
    expose:
      - "9001"
    networks:
      - template-rest-sql-net




networks:
  template-rest-sql-net: