version: '3.3'

services:

  template-sql:
    image: mysql:8.0.22
    container_name: template-sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: templateuser
      MYSQL_PASS: templatepassword
      MYSQL_DATABASE: template
    volumes:
      - ./template-sql/mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    expose:
      - "3307"
    networks:
      - template-rest-sql-net


  template-rest:
    container_name: template-rest
    build: ./template/
    volumes:
      - ./.m2:/root/.m2
    ports:
      - "9001:8080"
    expose:
      - "9001"
    networks:
      - template-rest-sql-net
    depends_on:
      - template-sql




networks:
  template-rest-sql-net: